name: Sync app-ads.txt to GitHub Pages

on:
  workflow_dispatch:
    #branches:
    #  - main  # Trigger on commits to 'main'
  #  paths:
  #    - 'app-ads-txt/app-ads.txt'  # Trigger only if .js files are modified

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout app-ads-txt repository
        uses: actions/checkout@v2
        with:
          repository: kevinanghan/app-ads-txt

      - name: Copy app-ads.txt to GitHub Pages
        run: |
          git config --global user.name "Kevin Anghan"
          git config --global user.email "kevinbanghan@gmail.com"
          cp ./app-ads.txt ../app-ads.txt

      - name: Commit and Push Changes
        run: |
          cd ./
          git add app-ads.txt
          git commit -m "Sync app-ads.txt"
          git push
